### ISSUE TITLE
Possible to make this active with friend component?

### ISSUE THREAD

**Issue by erich199** [imath/workmates#5]
Hi, 
I'm really interested in this plugin.
One of the features I feel is lacking in the group part is the ability for admins/mods to invite anyone. Currently, it is set so when one creates a group, they can only add people who they are friends with. 

This plugin is really nice since it allows a group admin to invite anyone listed in the site. I'm wondering if it's possible to replace the buddypress invite to group feature with this plugin even with the friends component active?

**Comment by imath** [comment]
This is fixed in [WorkMates 2.0.0](https://github.com/imath/workmates/releases/tag/2.0.0)
